### ISSUE TITLE
Ability to Save Scan Results

### ISSUE THREAD

**Issue by deconspray** [ThePacielloGroup/ARC-Toolkit#37] opened 2023-05-23 18:23 UTC
Client is requesting the ability to save the accessibility report scan results for an individual page to a file ("_would assist us in our QA process_"). This is more when integrating static accessibility scans of pages as they are being developed (or modified) and tested in QA (sprint context). 

Having the way to save the file to provide in a bug report for our developers was the use-case I was thinking about. Can do screen shots, but nicer to save directly to file to attach to a defect management system. 

Would want to save results for all issues of a scanned page, not individual assertions. It (bug report) would be more to cover
the totality of the critical/serious issues found on that page for correction as opposed to breaking down to each instance.

**Comment by ferllings** [comment] 2023-05-24 07:16
In what format?

**Comment by ferllings** [comment] 2023-09-14 09:43
Duplicate of #16

**Comment by ferllings** [comment] 2024-03-26 10:33
It has been decided we will not implement this feature. As this is a feature that ARC (will?) provides

**Closed as completed by ferllings** 2024-03-26 10:33 UTC
