### ISSUE TITLE
Add ability to adjust text spacing for testing 1.4.12

### ISSUE THREAD

**Issue by douga11y** [ThePacielloGroup/ARC-Toolkit#6] opened 2022-07-13 15:39 UTC
**Is your feature request related to a problem? Please describe.**
> The previous version of ARC Toolkit provided a mechanism to enable CSS properties that increased the text spacing on the current page. This was very helpful for quickly and easily testing 1.4.12 Text Spacing. The new version of Toolkit does not appear to have this feature.

**Describe the solution you'd like**
> Add this feature back into the new version of ARC Toolkit (possibly under the "Other tools" section).

**Describe alternatives you've considered**
> Alternative solutions would involve using other plugins or manually adjusting the styles in dev tools in order to test 1.4.12.

**Additional context**
> Not looking for anything above and beyond what the previous version had. Just looking for parody.

**Comment by poorgeek** [comment] 2022-07-13 21:15
Duplicate of #2

**Closed as completed by poorgeek** 2022-07-13 21:15 UTC
Labels: duplicate
