### ISSUE TITLE
Duplicate labels used with version 5.7.1

### ISSUE THREAD

**Issue by dinutraveltickets** [ThePacielloGroup/ARC-Toolkit#59] opened 2024-05-14 06:34 UTC
Hi Team, 

     I am using ARC toolkit (version: 5.7.1) chrome extension. I have two radio buttons with different aria-labels.

     At first time when I select "Run Tests" I did not find any errors. If I again select "Run Tests" it is showing error as "Duplicate Labels used". Could you please check and let me know the solution. I am adding html code and screens shots as well.

**HTML Content**:
          <div className="logincontainer">
                <input type="radio" id="check0" name="check" aria-label="Select Product TD0176038767 "></input>
                <input type="radio" id="check1" name="check" aria-label="Select Product TD0176089784 "></input>
            </div>

 PFA attached
        
      P1.png -> When select "Run Tests" first time.
      P2.png -> When select "Run Tests" second time.

![P1](https://github.com/ThePacielloGroup/ARC-Toolkit/assets/169297814/6c5305a2-2414-4033-9b65-d7cb5f9bca03)
![P2](https://github.com/ThePacielloGroup/ARC-Toolkit/assets/169297814/905ba119-8b76-4612-b970-da8ed77109c1)

Thanks & Regards
Dinesh G.

**Comment by ferllings** [comment] 2024-05-14 06:37
Thanks. I have the feeling that it's the same #57 bug.

**Comment by ferllings** [comment] 2024-05-14 08:35
Confirmed: duplicate of #57

**Closed as completed by ferllings** 2024-05-14 08:35 UTC
