### ISSUE TITLE
Regression in v5 - Reflow tool no longer available

### ISSUE THREAD

**Issue by mra11yx** [ThePacielloGroup/ARC-Toolkit#15] opened 2022-08-02 14:51 UTC
**Describe the bug**

The Reflow tool that was available in ARC Toolkit v4 and earlier is no longer available in v5. This is impeding testing for users who rely on this to evaluate 1.4.10 Reflow.

(Although it's certainly possible to test 1.4.10 without using ARC Toolkit, the checkbox was one of the faster ways, in my opinion, to do so.)

**To Reproduce**
1. Open ARC Toolkit
2. Observe that the Reflow checkbox is no longer present

**Expected behavior**
Reflow functionality should be re-added to ARC Toolkit.

**Version information**
ARC Toolkit 5.2.0

**Additional context**
Logging as a bug request, rather than a feature request, because this is a regression from prior Toolkit versions.

**Comment by sophieschoice** [comment] 2022-08-04 08:44
Seconding this bug request, I really miss this feature in the current ARC version :(

**Comment by poorgeek** [comment] 2022-08-05 06:46
Duplicate of #3. 
This will be included in 5.3.0 which is pending release.

**Closed as completed by poorgeek** 2022-08-05 06:46 UTC
